# Generated by Django 4.2.7 on 2023-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0004_counsellor_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="", max_length=255),
        ),
    ]
