# Generated by Django 4.2.7 on 2023-11-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_alter_customuser_role"),
    ]

    operations = []
